# Generated by Django 4.2.5 on 2023-11-25 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionformat', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=1)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ClassMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='MonthMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_name', models.CharField(max_length=255)),
                ('month_code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Sections',
            },
        ),
        migrations.CreateModel(
            name='MonthsForAcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.academicyear')),
                ('monthid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.monthmaster')),
            ],
        ),
    ]
