# Generated by Django 4.2.5 on 2023-11-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='enddate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='startdate',
            field=models.DateField(null=True),
        ),
    ]
