# Generated by Django 4.2.5 on 2023-12-08 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassMaster',
        ),
        migrations.RemoveField(
            model_name='monthsforacademicyear',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='monthsforacademicyear',
            name='monthid',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='AcademicYear',
        ),
        migrations.DeleteModel(
            name='MonthMaster',
        ),
        migrations.DeleteModel(
            name='MonthsForAcademicYear',
        ),
    ]
