# Generated by Django 4.2.5 on 2023-12-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_delete_classmaster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_comments',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
