# Generated by Django 4.2.5 on 2023-11-30 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_department_studentid_subject_student_subjectmarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='stdent_age',
            new_name='student_age',
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='studentid', to='home.studentid'),
        ),
    ]
