# Generated by Django 4.2.5 on 2023-11-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_stdent_age_student_student_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentid',
            name='student_id',
            field=models.CharField(max_length=50),
        ),
    ]
