# Generated by Django 4.2.5 on 2023-12-02 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_studentid_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_report_card_generation', models.DateTimeField(auto_created=True)),
                ('rank', models.IntegerField(default=-1)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.student')),
            ],
            options={
                'unique_together': {('rank', 'date_of_report_card_generation')},
            },
        ),
    ]
