# Generated by Django 4.2.5 on 2023-12-02 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_reportcard_date_of_report_card_generation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcard',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentreportcard', to='home.student'),
        ),
    ]
