# Generated by Django 4.2.5 on 2023-12-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_reportcard_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonebook',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
