# Generated by Django 5.0 on 2023-12-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonebook',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
